export const NATIVE_TOKEN_SYMBOL = "CGT";
export const PARENT_TOKEN_SYMBOL = "KSM";

export const DEPRECATED_STABLE_SYMBOLS = ["USDC", "DAI"];

export const BASIC_TOKEN_SYMBOLS = [NATIVE_TOKEN_SYMBOL, PARENT_TOKEN_SYMBOL].concat(DEPRECATED_STABLE_SYMBOLS);
